service:
  enabled: true
  port: 8000
  targetPort: 8080
  postgres:
    enabled: true
    auth:
      username: postgres_admin
      database: user-service
      existingSecret: postgres-password
  secrets:
    #postgres-password: AgB4iP++ZawMt3mrI6XGU7UjoJNwoCJnYMM7pi7zva6k2mwr3jdc3yENMCbBGzFqpshvr8/0r9bf39qom7LJov6tVc59DJhPKMMeeLsetiNBb/H+vzDxDLman1z1XZ6wY95uUqzs16UzjlSDl/NwwzJCYSjjGQLLX2IZEp5njEwp+hkEmmOF1gUhqJxFUWxmiPDE13cUbyIFo0Br1GRv1Bh9n9Ow4V6XCEs0NnUIxBKWCjVG2mYhDw1/lNbuNtwdYtoo0uSsNygl8UF0+DFuhPue+5A2Y1p0MiJGEwrJTZ1DgLMjwWtPCgBZLbYWbwa1vijnfr/OtsHg+HT6JHlsPdS0u+hYzGh8Edanfs+jnP2Th+1FQmRERrdXqLW8fxUIPTw70GXeZcIib/7AUohfVPWaj2Pr6tv8J2/L+FmsH6a2OZhqDW2z5Q5e6UFcraSmKFmAouuJMMw6UB2l7AZHfeX1h8Cj56ppcVUeRT3eH3h1XIjd2OoYzG6PAg7QgVaLcappWL2sIwIFW8EowTgspMuETwhZ67uG5UYW1InSdZIo/tN0tY7BQIf3uI/GfE8gRVE/pUQdw1qiPwJaZ56PJidggO75mkUIfxdiDs4qBQv8s1yPzFvKtqlRAUnSskBBi7rk8xLb6S0pGv4KTueSga+1Rp3HAaVYcRweJ9pC9yWA5uLU+o2PM5Nc4VFMrBaN5bRs/tOACXzcOht4mi0OGI0+RFxrZNBHmVz/h76A
    postgres-password: AgAcfI0pFaDDIxtx9qh28zhuWCwo0dqqff0SrMt1CAI8bH3GEf3a35Jqw0ZXrqdK1YB1YLW68cLRlF5cCiFwFHBTu09Za7H6xiTj+F5zTcNGBrJG4GpoWdNqX681joqSXVBqJH13M3d5c8R3Xa9u13YY/0pvVY1y/DoGIqC8F5op62D7XGm3XYFViTjSo9m+yd5i7Xe8XeI2eEup09LdOOVFvPvaxY6TRWKzruf9WJATBvg3rIbpS8zNhPOTt2+tAW+0w6nPSFdrm1c0Wnw48xpXGnTx0Lmgu/ibAscltHWiuyIyfbIkyvvLAyG0HwbqDmmU5/grHo197CyMdnni8sm+IO41P8N4wC3q9iqr89jYocBE/JHJp1H2IQnxGA6vF+iurE3v1SWrak4FN83bwt0lckkKMX0UBahi/uKYmfWjM4/I37Bv7gM2raF73IQLC+tvxsWe4JyiC+k4W7a9jsuU9Nb73Q+sneiWIles4KGrAjJHm+aH+St7EOvMYQ2rVuVMzhK33LD7eZI/TGIXFrtbXPli6UyOsyuNds5VF/xrhDeIr+seE5+ilm32/9WrQSfIeGKGuoq5ixw9tT4+eFdGTeWXdcrzqJi/Ktw5PhGlDiET3ycg0d1IU+ouS75hJQRYAPsPvPaBXFtXFUpZq1Kdd8E9eEFoWgwlFzKP9SHM0m8wRpltMNdUYb96OC1Q225RAGEfpyGyQv6M/LMvaN9n3WplILgMp/3tj7bo
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: "5432"
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: postgres_admin
