service:
  enabled: true
  port: 8000
  targetPort: 8080
  secrets:
    postgres-password: AgCRxl0XLXQ0UY8AP1r0ubpSra9NXVCXwOPOjN+Qv6D9SU3VZEuFkAWvffPkuBr+riVzPpMgr5Tot4JctKTxYWUTFthQnp3Cq9LwtA7pj574hLKRX9mniEY/OBTNqFXTJ39Gssx+NRB52mfy9LxJsI9myKqqc+z9xFoPzDWKvb+vtGh3EMz1Arqt524IoWynnRKORzj31BEG5fJduP9V8tUU1dKdNMYVxyEGOy8CMFELJXEhpMZRvf9ts4KsCdYkUT+yg2J32mEC0tOqLogM01SYHN2UU7xda6ohE0UQWOd7MzaCmRtHGQDPAnFU0hgQnvMeIbnkv1XCpFeNY/vZR27FmLeJm85uJ8Pcrx69auW6TCOHg/j0ziAmAq8xK7oQpUYkvh8zHqo5HFpG3Z0zqZ3GXncvTAVTwJhY6Rfb+4La+iYrP4GQ8xoZyWBpC8JAS4tanV+fDE81wizYCyE/5kOF5eClaE0hAWTsAUfZXzoX3sl07i8sVERNFmtv6DdfFzeUGcieKCZRKuTyLPIFmvrDqVhv+aO8ZwGdDqiyhGKfBBHCqA4U8wfsIoq6izn+FqZusae9aDyondvPKTMZUcYLH8TU0PLGSB7fqDwPc9jX7WkxEeYgTyl5VpXhR1KhFY2CaKLSVUirSVzp3v8X7vdDJcRzKQEchuegIFVdjfVUf+tF1A2RCDpU+CxvV+Wqy9l7YV2DVNavPy221kIcqaRrtjXLH0fJDOiCBVxo
  postgresql:
    enabled: false
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: user-service
