service:
  enabled: true
  port: 9000
  targetPort: 8080
  secrets:
    POSTGRES_PASSWORD: AgC+BsIO2CSUiUbPVTBnYx7Wtc/FMWpNoKQE/Cp3FWvaSAK7jmK0xOKbQG1txyrta+4hzib36cx19dgoHARws58vq8ixYqjFlWTn2BSqQD3fn0lggtIY1UVZNqqVHnJ326qwWPV7XQBUlYOjNyVJ3xj0AitUTh5+4lDwFIMciU9Mtls6olBx7J8i3COXb1g/HgvmTmoqVg5Y4M2e+vB/cSpXRb9qVhjMQkYGSxb7DYtr6Y7rlDQcI4thaULsPy8Low4rzyVU4vKskpFBBybWEidI1ZFEhRqP626cqKMVQHRsuIMos6vC0nCBN8uq9yEjlDEMJXYf9OBHwxoC9QgQg+C8Aj1VNEnvUXbEJA2MStECurAmXpcW4V28VXLNXjmNgqTfmWTHme1xMLbgD4piWDjsS5o58osFJbF/kkUNlwnEsa5f/UZITkZI9eMIe6nkdT33A3CVvhJ1dZn/PXgo8mFKX9K8MHmqmxO5zJI4S7O5YZUYVBXtOzq19LtFevbbyjZF/uJDnmJG9ZTlgNvqyDgQzFxP2+woFHnpq6aNc96VDsaCNJWCkqN+18NlyGNb8RhhzTgaZyG968PJoE8PyXTq98bzBbyJ9x82w/jK55cXjbdH/yqn3l1FS+1OnNEQpNH7vw290nGdj8GKLqNe0x8pAPtnWI2t+if8Rkul/VzedTGXzN7g8xjjqyIu3zOIsZqfMxBzSP64+rYU+z7yD1uZQkAxZnHzLog=
    JWT_KEY: AgBlbwQXGpTjUlehjkUOaTOwwZNileL1pW+xs6f+lZiWWTfMMevN2fNdI0gi65q0iJqt14f47geiW27l0OrJPKkjbcXxB3qAY/BN7hK7rh+o87czqxJBmX30YJK7VDnVEWUpReVapuDTdeLbpkF9v3o7t6cenU/A/nyskbjL5DB1Sa1ulS8D6dXZz1vQrkQuF2sGD6+lJdOhbjVXJg+2ik7kDZ7tba1G4qhxOoC9QLDncDwvyX7TxxGQQsLkCtD5+/woe5U1J7S/rW4L6BxKkmrA425TTdGvHl1nWDUIEbvhcEvDcxr9JA5TIeMV/0Sv8QXoEFxGQ0KnKWlYebA+r1x/7jkrQU8ElkLi2G+YpiPj3NCb6dUAFqKVrxA6Xnz4LFEBxKH+xRF3W8peZfLtXJ4Rjn+ex0LCog+g1QEflANjIFo+bywYI2QHgX4Zlz/hs1ys1JdulV3XNxMHgLfvNa98ZCoFDOkW8dzpDL4cr7lVGfKCB90puknt0Jbkoq5Pqe/GlL145HdwFwA0LKN0kcP3CxAgJkuDRI0G3WZ1ijbgdSqF6n6eWH8NyAp8gPL32iA2gt2704ITyh5jHAeEoBQMuT7L9VWU9FWjPQVYmHkysbW9AL2nvURs7MiXKKig69n5++qVMo5VmOQ4X1AE9MQuoKZ8lnfCdUip4qM74CTm7kYwwqg97rgtee5LI1J8K3yLls88nDwfRyEkWj0IeFSOBLbXLDdI6HDtUE3VL8XzBZJYRgqf1PWypKoZKCqzoTYKL/rwAUnxQEiZ4KOsbmJN
    SENDGRID_API_KEY: AgCzNDawykP9W+RRUY2ZfDGJG7yoCASgBpgPWngfWorn73HN58UdFuBT7JXssp78PjO1wFY1UEXyZRwhnozB+8WlK1IKKTIApfScFkczP9vAvCphbECmhgf/A5fMcC5L0OyDmGgyVWpdGKXzYWoCv2vzlY9V/uAmgH0it/1/aLM5RMzNns9/Eb4eS8s5mBQgJ5v/DxWg2sFTuBQRO+DcH3yWHy2Xq4zBApi6+eaa+/TVYCCaKWEUPZPLd/O81euByUwgQc+NXuDvF+jLy/Iupl+hWOQTD43SOvUAENRFiluC/+N5M60RYNRiyGduxY7BVagytX5fRZQXp0corP8OzSiIekwoHRrt+c/qKHEl55m2ohEvhpLMSNKOwcmT+iUpXsbN2jBmi8tE5jDd5xztiJ9KYGzntWHxvmWgWsEyk6VSggzUaXOL9msQAKMg1omc+0IQ2/GIQNcH7WBoWgZpmMX8nGAHSXmLZDxNWHYOC0bpfvpXV6Sq/ckCBILAoVSxkVEdcgeD01QvGC5wbUXKvJTQHofF2Zlg2zGRr4ovLLlFIguEzXfCoLD3WwTYAU9rJrVD6t6e9KUvmt05EGOA8kFYfjZbcgKynKn69iLcfNRwkNqTEIlzbj9NHTodJxutF7KPs7CfXYOJ4+kvoV/salwDol7c8TJsLfSbeo10d9qoK9mLaYdBukXM5TwRg5R3Yy41Sbiocr5AXPTbww/ht4nEpI9Ty3DntEovwZ2q/IEYGe/QsuylJ0QGKOkWkSO9MrN5lmAVIInCWcn4uZ8DlL10BXxveKY=
  postgresql:
    enabled: true
    auth:
      username: service_user
      database: user_service
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user_service
    POSTGRES_USER: service_user

    EMAIL_DOMAIN: thirdplaceapp.com
    EMAIL_PREFIX: test
