service:
  enabled: true
  serviceType: LoadBalancer
  port: 9004
  targetPort: 8080
  nodePort: 30101
  ingress:
    enabled: true
    paths:
      - /user
      - /session
      - /otp
      - /forgot-password
      - /invite
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
postgres:
  auth:
    username: service_user
    database: user_service
