service:
  enabled: true
  serviceType: LoadBalancer
  port: 9004
  targetPort: 8080
  ingress:
    enabled: true
    paths:
      - /user
      - /session
      - /otp
      - /forgot-password
      - /invite
postgres:
  auth:
    username: service_user
    database: user_service
