service:
  enabled: true
  port: 8000
  targetPort: 8080
  secrets:
    postgres-password: AgA2qdFulmISFxLl0NI4Th9RKS68h4P6wDD7obnQxhvu8L+zrdKug8AC9oCsrdB9tL01RjXmQNPY0uwae7KQRcgYsk//NmkX6AXQirYTr0b1mbzDVFjyOzy6Rusqc6UF2BChEUqBfb2grbYJy4+agCWlConvMhjZBmaOztXQgQvo1qZEELqtWD6wkeaH6DTR0KAlNClSzqUuF/Tk/q0RKbpGeQDT6W3qtO0nc0Q+yRgroxRv6a6Wab2KqDH7qzYciWdj9Rpd7Msi6YsC/zUDq7+OA/wtuZ6bAwLVA8tZeXwkCyg9dx+7I40qrWJNakjeMdnHb9kV5GmBRNCpKskULqlSe7FQ2cgpz5STdnXBI4zPlO1oJlcjeuVwBKpy11SH1j0hd8tGphhOj+joBjaO4yV8+ROxYW7z05o7BM7gS4m28y/OU/ofi/2iM2+WJKUa3+22P+L/usHOT32GdQqO0NTEh9eed774sEjfz+tX4WnpUcqwaJt0LnWYVc1mhiwWkz9sXmt6lggLklDE/Md83FqX3ERcSPvVfeZNWpxmfRaPAL+S/tusmPyah7Act/gcLp11krKFVj/CycQtKvwFAs6sDyW92nzhBiYUFrg+acUoYNdLbUmQPEWPeYffIm1BkaC2cZdwDFMgXaNsYq8ymrDK0MidvhN6dpemlFkNIgBPD9ioh6f0cEgSZhJ9rLoxgOCbUP0Jr+utCrpbd53PkqY74iQAcLsZCsSD
  postgresql:
    enabled: false
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: user-service
