service:
  enabled: true
  port: 8000
  targetPort: 8080
  secrets:
    postgres-password: AgCm3n4fYZZg6R5EetgEmU1CbCPS7X3GvRr/+ZZehlw2iNx2OGC49UgihF7A2qbfA8X4vUFmF0C8WtRDzXUUT8aqw9uBY+ASb/ZQE7LvSGGWdm3/Tt8fxtTIIpID+usHD02H1ajBUqCRhdSgeTv4xXwllgQQ5X8WG6ltA6cPPyxr8WGhI/Dje4vm2xqs/6SAcGPBTh3fQmAtoQ49iV3IY+OVQoqHsjjeZ5DtwgdlQLzrAT3eDNdMac76Ts5WP3S6+th4hieXH5ZpVGHopc4TeFaeYG86tCBmCbp82P3dZjCabT2qKVz4ae90NZZLG+/xMVhoz+H+M/TtWiA237cD98nRVlm81Auf4xZmVzWv/BLxM/5zqh5m4JGcXLnVc+PAbN7Wy7mROs1ngMR1nDIgIwgACUnGUdHIJUWz3v2NCkyI2pmWizuH6H4/7YiNb05FX6it9vlgselV8otCVy9uP7CLXjrZ64tO+pJwQjt82+dsTSPg6lX/aNwQcc29t0imtp3hl5wM0iN9k387TCdr0jv0F+AxIALhZTOTnIUvV59Wt2/bDVyt2AU9c7YmS4mAqonuUMQgXMG4Pc9VpD9xK5i1vsYQABBgFThGNNbmSujXqqCQDIOGA5T6nhemZIJ1OtMJJjIuKKUpA9hX55XmNXiWy8lO7Tdjx/TAfb9qQe3yZGAeuEI+veyA42Vb+vqfFBUGzlj9KrWRYWciLvfIk29kOho1s9QF6gHgfRnM
  postgresql:
    enabled: false
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: user-service
