service:
  enabled: true
  port: 9000
  targetPort: 8080
  secrets:
    POSTGRES_PASSWORD: AgBr2IQT+wazFt4sQ4qBeER1bkB6qK5kyt0tcCJ9Lc76KnR3xLu9sJp8pNVajJx1iQnfoSbzwlirL+SMSryNXy9KLwBLtYY4V24otDugl6MVtYwYMNZczUXTlzwp0RMrhW0WgQDlsoTHHr80XHkukYBUuYBtzk3k7J2kGDZyiTSlmVvFMZ7o0+dg1zcqdyB4WaA+IzZ/4ev8sP6Pox8vfzu6U7TooIyHQNOWZB6hgV4nObHOURK/wHNRwzLbQ6RnlFJ1z5M3DsaaCgPNXrAMJLExy58h9FjUfzu+2uoiO1s1RzkFNi0Mmy/WD+k1YuzEhV386Gpiijd/AG3OOmnzL4EAnyc7abimQZOnhKK96qUmvyJISOncEsyIw7NgT9F42x3Re1SwP+xZZQWXcdKJloPxjhPhTUJdUjLNmn9PsJuDog/8U2jErOen99pIPNMZQHTfFt4KYQ+GwcPlSrjLZiYiPyVgr8yWKylJeOWlfxfBtvldjn767qgNQAw5NtFRpZiUZd+y+5DmFzm9ierZg7crGwuoGvTccz/hJjT8rfkEPi40Mk5KyUf5MrwgKHi8px7TJskd/j/1wkClMz+BtJ1TL3TDFVARTk8G0UQ8YySZJ7UZZD99HT+7/O5e6KxMZbeTpVZmTZNDKx2LgJUQriGduPZQbPj2/Nun0fVTLJYNEr5HMZgKl7aBuZ3BE4AK896jMbP9V7AjpVEHNFY1MjaWDxtGAAchgbk=
    JWT_KEY: AgA7eI3BqMKO50zv2hPuFM9xDLO5gFkDCQu7TMIP8mz1UlGeOEYRAeIhIPqUzvqyVwzc1Uvg9z0NqHE8eE4/rR0ClZYQ1Etryxfixypu48y0Bs7iqxbJZpqL+EfUFaLXU7yHVRkfA4S1pjbLJykWKxta8X/aknpFdvGtgHmByFD6KsdOFtanjSvRo9NgBhTKT8uj7snS08+4k5M4Q+iM9hr2VI+PuWI4sNlrzJ6mQqStljg/X3z6tu35ET0uIbSks3UqZf8ojbIAuIL1RRV2hx2JGuKpVTSzegVCc8fwt5oesEeKteZ7Hmy2yP8CRyWS7jmKrFxi2svxSAV7+Ah0H3flA94NPKyWK0voJ/6KDGGKODBdJ44LL91ZtyUrVMc/7yiJYBD8T0TYUen6icvaBI+lXEcsFix0PuJ807o9ybO9Mz/DEIldvrSETmlsHIvvpqyl2rFJWoWtv0X1flX0xUuMC4dVlDUvLCFDvxtxPwgGQyl0wDS4W80AqbIpgd+KvjVB5YU25BOP558ag2SyGwaJoJORMeSMjAmjjzGK0Vhj6QayvJnvCZiqpeXkNSWycXE58ULcU4r/0OCjupNLveioqP+CiAK76R+SD+zr2YLwiUrcAkcI/puPqF3PEJ/9nm26ExwNDHDgtIQDficQyeR0ezoRLXAZWAdHAz40kMoQsE33G2EURkJPvAFWpzTRGPLgUIgKIBRGbmNv7WR3VX2wiOtddgoVof4058cwuRIMpVEpkTn2DA95+SNsYjnnaTBIEeHr3q+Cv82qsjl244ZAT6zcvw==
    SENDGRID_API_KEY: AgBprO2HDpmzxGB/pP61AdsIfFSVXPljLU1flzDxKb+BaSfDR6wYtfcd3ZPVxtRQE4jKHnhJ8p0h7clFHZNVueMhshjhi+50FF5LZUSp0GxRZFUmLLqcYA6Putt4u5GsMS3xI/idRlWSJwZOmysK9y71dW2dfxjKPKjTIL+alckLj5p9/Z0D4Qyq8uTZb3uyFPZ/cPLxTmirMCy3PhImDh3WU1HAge6DHlkfvXuHUhJ7N9FrxVu24AB+M59JDYjdPnfwAgq06oWeDjLcgFB+hQWaV2Hx+gkgvE+zZ7hloD70oxU5egBLYGGdQ7qgIVSMvnlll2MVEJVtkPv+ztjQYkUXouf4j1OrfWIoLCXJ03N3UVpsI5j5bpJvkLFJPBra2SCjoelVPSeKjEVBA0eZIVaqO1RZfdW3V947ObrlX5rMILL9Yb1b5pOsSlACwfvkVc+PuEgIhEg+pDCx2uKKSyizHh77kcFMsGMA/6yLTkHL6AdDxHcBUwBFeHUBS5w9EksXyZ5IPT8uLebrhpVk++MzyYWlEfN9nJoXL5n0aJbXo1/g60JrE7iTP0s4lTHO8FiLiRKBf6l6l9ZEVLIYQWEBCdFCVI5aD/ZgKtcqs1CBnPkNrh9LZSj8kHD1cR6ayIYOH8Zq//VuvftIvP4pd1WsMkpeGDN2xcy6St+n+BDFtu9Q1J7iMmlyxLDLrOx+8c7f+TsDlftM8SpEPo3t0J3CjbZdvBr4Og/wDpBPphcVw0yzAeVviuYXlQz/4JQim95KN7aOThoYXS655xh6molrX5MAI3/+gMdy
  postgresql:
    enabled: true
    auth:
      username: service_user
      database: user_service
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user_service
    POSTGRES_USER: service_user

    EMAIL_DOMAIN: thirdplaceapp.com
    EMAIL_PREFIX: test
