service:
  enabled: true
  port: 8000
  targetPort: 8080
  secrets: []
  postgresql:
    enabled: true
    auth:
      existingSecret: postgres-password
      username: service_user
      database: user_service
      secretPassword: AgBr2IQT+wazFt4sQ4qBeER1bkB6qK5kyt0tcCJ9Lc76KnR3xLu9sJp8pNVajJx1iQnfoSbzwlirL+SMSryNXy9KLwBLtYY4V24otDugl6MVtYwYMNZczUXTlzwp0RMrhW0WgQDlsoTHHr80XHkukYBUuYBtzk3k7J2kGDZyiTSlmVvFMZ7o0+dg1zcqdyB4WaA+IzZ/4ev8sP6Pox8vfzu6U7TooIyHQNOWZB6hgV4nObHOURK/wHNRwzLbQ6RnlFJ1z5M3DsaaCgPNXrAMJLExy58h9FjUfzu+2uoiO1s1RzkFNi0Mmy/WD+k1YuzEhV386Gpiijd/AG3OOmnzL4EAnyc7abimQZOnhKK96qUmvyJISOncEsyIw7NgT9F42x3Re1SwP+xZZQWXcdKJloPxjhPhTUJdUjLNmn9PsJuDog/8U2jErOen99pIPNMZQHTfFt4KYQ+GwcPlSrjLZiYiPyVgr8yWKylJeOWlfxfBtvldjn767qgNQAw5NtFRpZiUZd+y+5DmFzm9ierZg7crGwuoGvTccz/hJjT8rfkEPi40Mk5KyUf5MrwgKHi8px7TJskd/j/1wkClMz+BtJ1TL3TDFVARTk8G0UQ8YySZJ7UZZD99HT+7/O5e6KxMZbeTpVZmTZNDKx2LgJUQriGduPZQbPj2/Nun0fVTLJYNEr5HMZgKl7aBuZ3BE4AK896jMbP9V7AjpVEHNFY1MjaWDxtGAAchgbk=
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user_service
    POSTGRES_USERNAME: service_user
