service:
  port: 8000
  targetPort: 8080
  postgres:
    enabled: true
    auth:
      username: postgres_admin
      database: user-service
      existingSecret: postgres-password
  secrets:
    postgres-password: AgB4iP++ZawMt3mrI6XGU7UjoJNwoCJnYMM7pi7zva6k2mwr3jdc3yENMCbBGzFqpshvr8/0r9bf39qom7LJov6tVc59DJhPKMMeeLsetiNBb/H+vzDxDLman1z1XZ6wY95uUqzs16UzjlSDl/NwwzJCYSjjGQLLX2IZEp5njEwp+hkEmmOF1gUhqJxFUWxmiPDE13cUbyIFo0Br1GRv1Bh9n9Ow4V6XCEs0NnUIxBKWCjVG2mYhDw1/lNbuNtwdYtoo0uSsNygl8UF0+DFuhPue+5A2Y1p0MiJGEwrJTZ1DgLMjwWtPCgBZLbYWbwa1vijnfr/OtsHg+HT6JHlsPdS0u+hYzGh8Edanfs+jnP2Th+1FQmRERrdXqLW8fxUIPTw70GXeZcIib/7AUohfVPWaj2Pr6tv8J2/L+FmsH6a2OZhqDW2z5Q5e6UFcraSmKFmAouuJMMw6UB2l7AZHfeX1h8Cj56ppcVUeRT3eH3h1XIjd2OoYzG6PAg7QgVaLcappWL2sIwIFW8EowTgspMuETwhZ67uG5UYW1InSdZIo/tN0tY7BQIf3uI/GfE8gRVE/pUQdw1qiPwJaZ56PJidggO75mkUIfxdiDs4qBQv8s1yPzFvKtqlRAUnSskBBi7rk8xLb6S0pGv4KTueSga+1Rp3HAaVYcRweJ9pC9yWA5uLU+o2PM5Nc4VFMrBaN5bRs/tOACXzcOht4mi0OGI0+RFxrZNBHmVz/h76A
