service:
  enabled: true
  port: 8000
  targetPort: 8080
  postgresql:
    auth:
      username: user-service
      database: user-service
      existingSecret: postgres-password
  secrets:
    postgres-password: AgA44PCEjBXLZLN9BnBWSdNydI25EuwxTy6g3U4C6rVPECaTEfzchuTA/AuC2bbRnbM4bVtnU0RrRFPGGR6scg3NHKgUrQWTejXRP7U6xBgzoLUGqxqFbPgd5qsLGdinCRA7oOEvKJNKXtDoKtkIsLk9edIOvDQPb12Y/G/wgYY4NM7zmoxktNSui73Ap1+LzsmnvpXq4eU9+Fv/lvsvyyoVN3FAM5cLs8tETf2pGNB6K+cx6hUkuT/1xvMvDG+7p5CLMu2Nw8/X5ZPf1ueQJ0uf47Ce4AgCldgXc9WvxCbbIqUcJqdpHC55mCFxEC/G8JlX+WdfdsKiA/8v0cxYe96l5kQfRhuZJWQ1z+Schw2KhjaL7G4tfsokZ53mlPKL7yDC0aZB5V6szEUTtibk/dqNIiFa1VKNvGMDDWs+tBGwh/k77qYvfTJrkQPzXAvsRYGNXa8efCfksYkpxkd5FCR6c07KTIIvDMADD7vJUinrYdL/fHvCgHxLtuvi4Rl3KFxRKFr03LXJA4107AA4s8YWG2yh1NVOPEUKWqsW7IJL4ZlD+qvqddOvWIWhgwt0UvRGvpyvT7F7W2HdOiVqqm1dqrXC3f/cYGFIl35o7WZxfYcuuEdJDKw90oZMcDfijaUSwHc88dOk9enEMoO9j40623vpCObZl3LWAqvHCOpXOeWIjo1Cp1dGdAwsqVLvs5WvvddoZXgkl3GcajKabqofq8P7ykwpUnY=
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: postgres_admin
