service:
  enabled: true
  port: 8000
  targetPort: 8080
  postgres:
    enabled: true
    auth:
      username: postgres_admin
      database: user-service
      existingSecret: postgres-password
  secrets:
    postgres-password: AgAvp8LUtAcEnbsNGc1RMBu20F80l+XREHuuugQN5WMCVlTshOFcFggJJbhKh8QLCUB8FIqYyW2NszmFJRGcDnIhewyLqHqt5V3GzfLriOND9h2v550F5fCS+A3038GNINJlLZwNmcQrzfjDrwah9nzFpTfAYIwJIZ8/N/nTP0b5scEVQktZf8vMCHLoKJo1ZpNbyIy9dcSdvKc5SkTO+DCcCcJU6vCzubSvXmuFmV8EkYQXud0myImYarMsamTajDzcG+jX5uA/LszEKa02CBcnMbADEjQpsowO5PLjlxyCwwDDku0y4kC8C/afhoSq1240YmUzR/AXaScxoJcFfVgiQQM8sFRoUtS65abnikV9Am/xB1qwQioCKL7MZIZDjhBZBTorMNa9AnMpWYvMrv8lxFVXVH1PT0w690tdkJZIS2YyfP+sn2uzDcjlCibIAUCpoINHjcTSci68VAgkU8C20DvcJqeiXTo8VU7w5sYpYlzD+YOEKUGx8ufWUtSHrmmlv60liWoevNl/2J6OJOnw9g98xAkG9v8zH2ecm/EReXzOoGVFa1vJytRa/P1I/V2lIjjWOcnt5KzJF9/5X2vPKLjZIWf3rkA0cYgZc+pLwC101ANV/tNIilwWBLRjW/w3nQrPVFjXv9sEM1cWlAVAnljm7r2CcGQJyK2xMfGz4A0Lqeg3wvr5LSYx8Fg0eojQQrBG0ukMn3WmRjJR2rliWmo4LJCTNp/bETEr
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: postgres_admin
