service:
  enabled: true
  port: 8000
  targetPort: 8080
  postgres:
    enabled: true
    auth:
      username: postgres_admin
      database: user-service
      existingSecret: postgres-password
  secrets:
    postgres-password: AgAjEoDBd2+C3gi/TnzJNC7wGafIKjAfMUsOcTxZeeB/L76Rbc6xaJpyEi2XskPDFotpqY6FVzV06oFqxPsjKQ5OHihXqAh9rE+1UL//Bt+Hl5hNO07W3YdUbhjbm39gV95KihmgNj1gxq6xoEwNOhifRidHlalqqxVBENNcEdnKl98pUV7JC13/UtpFpytyVTQRMc0mhNN+9Tcir/Bf66zEkA9UMLswjIpMKmvpuwcJZIvmW4VX3+rc8dRa/oueINteErJYk6gqwKkytCUQ6o1x9/CmwuX4uSH0BLKThFSZeR+F0dDr9WQm9UyFluhGK7sk1dffycUMahKm/hMqJc6LXZ8ywKzFPkkGNNHsKxZZYmKegwVm7XymYJVx+5z/O3XpdtrUKNLPJJxv/P1bBmj5S5yn4WTXWVlYVdS3iLNnAYenxuszBlqpd3C4RJ7HLKjQ6MC2j24QRzaFQHgyfSWYD+7yeeIWlPfSGNy9yJ5a6Uy+Fgo6FFIIxQPTe7PkV9jk9gj0titKZKA4mbPxC3LrhhpDcJsP6Lz0IYSou4xurqsdX/aFyiuQ/46g/REWYnoseUuHYajfYneB2lhQGOBH8oybeoNfdDOO/1tgAmAdojyE4NNEvTr4ZhHsehe3/6bCqGLkbJSmb5XuRWwiIZV5jEGlUGuz9cbOI2gEs4ag/dDPQNxhr/jTL+JanDmSDmEI6m2R//ikMALfzmtB/ZcmI6IM/nm3dYDxTnWT
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: user-service-postgresql.user-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: user-service
    POSTGRES_USER: postgres_admin
