/*
 * Otto image service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"time"
)

type Image struct {
	Uuid string `json:"uuid"`

	Filename string `json:"filename"`

	Key string `json:"key"`

	CreatedAt time.Time `json:"created_at"`

	Link string `json:"link"`

	User User `json:"user"`
}

func DecodeMessageToImage(message []byte) (*Image, error) {
	image := &Image{}
	err := json.Unmarshal(message, image)
	return image, err
}
