/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"net/http"
)

type NewSession struct {
	Email string `json:"email"`
	Password string `json:"password"`
}

func DecodeRequestToNewSession(r *http.Request) *NewSession {
	decoder := json.NewDecoder(r.Body)
	var data *NewSession
	err := decoder.Decode(&data)
	if err != nil {
		panic(err)
	}
	return data
}
