/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"net/http"
)

type Otp struct {
	User User `json:"user,omitempty"`

	Code string `json:"code,omitempty"`
}

func DecodeRequestToOtp(r *http.Request) (*Otp, error) {
	decoder := json.NewDecoder(r.Body)
	var data *Otp
	err := decoder.Decode(&data)
	if err != nil {
		return nil, err
	}
	return data, nil
}
