/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"net/http"
)

type PasswordReset struct {
	Email    string
	Password string
}

func DecodeRequestToPasswordReset(r *http.Request) (*PasswordReset, error) {
	decoder := json.NewDecoder(r.Body)
	var data *PasswordReset
	err := decoder.Decode(&data)
	if err != nil {
		return nil, err
	}
	return data, nil
}
