/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"net/http"
)

type SessionToken struct {
	Token string `json:"token"`
}

func DecodeRequestToSessionToken(r *http.Request) *SessionToken {
	keys, ok := r.URL.Query()["token"]
	if !ok || len(keys[0]) < 1 {
		return nil
	}
	return &SessionToken{
		Token: keys[0],
	}
}
