/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internal

import (
	"github.com/third-place/user-service/internal/controller"
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},

	{
		"BanUserV1",
		http.MethodPost,
		"/ban/:username",
		controller.BanUserV1,
	},

	{
		"ConfirmForgotPasswordV1",
		http.MethodPut,
		"/forgot-password",
		controller.ConfirmForgotPasswordV1,
	},

	{
		"CreateInviteV1",
		http.MethodPost,
		"/invite",
		controller.CreateInviteV1,
	},

	{
		"CreateNewSesssion",
		http.MethodPost,
		"/session",
		controller.CreateNewSessionV1,
	},

	{
		"CreateNewUser",
		http.MethodPost,
		"/user",
		controller.CreateNewUserV1,
	},

	{
		"GetInvitesV1",
		http.MethodGet,
		"/invite",
		controller.GetInvitesV1,
	},

	{
		"GetSession",
		http.MethodGet,
		"/session",
		controller.GetSessionV1,
	},

	{
		"GetUserByUsernameV1",
		http.MethodGet,
		"/user/:username",
		controller.GetUserByUsernameV1,
	},

	{
		"RefreshSessionV1",
		http.MethodPut,
		"/session",
		controller.RefreshSessionV1,
	},

	{
		"SubmitForgotPasswordV1",
		http.MethodPost,
		"/forgot-password",
		controller.SubmitForgotPasswordV1,
	},

	{
		"SubmitOTPV1",
		http.MethodPost,
		"/otp",
		controller.SubmitOTPV1,
	},

	{
		"UnbanUserV1",
		http.MethodDelete,
		"/ban/:username",
		controller.UnbanUserV1,
	},

	{
		"UpdateUserV1",
		http.MethodPut,
		"/user",
		controller.UpdateUserV1,
	},
}
