on:
  push:
    tags:
      - '*'
jobs:
  publish-dev-docker:
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
  deploy-to-dev:
    uses: third-place/actions/.github/workflows/deploy-to-env.yaml@main
    needs: publish-dev-docker
    with:
      tag: ${{ github.ref_name }}
      env: dev
    secrets: inherit
