on:
  push:
    branches:
      - main
jobs:
  run-tests:
    uses: third-place/actions/.github/workflows/run-go-tests.yaml@main
  publish-docker-image:
    needs: run-tests
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: third-place/user-service
      directory: .
  deploy-service:
    needs: publish-docker-image
    uses: third-place/actions/.github/workflows/deploy-env.yaml@main
    with:
      env: dev
    secrets: inherit
