on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to deploy"
        required: true
        type: string
jobs:
  deploy-to-prod:
    uses: third-place/actions/.github/workflows/deploy-to-env.yaml@main
    with:
      tag: ${{ inputs.tag }}
      env: prod
    secrets: inherit
