on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go vet ./...
#      - run: go test ./...
#        env:
#          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
#          KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
#          KAFKA_SECURITY_PROTOCOL: SASL_SSL
#          KAFKA_SASL_MECHANISM: PLAIN
#          KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
#          KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}