on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go vet ./...
      - run: go test ./... -coverprofile coverage.out
      - run: go tool cover -func=coverage.out
